Repository flatpak/xdg-desktop-portal, pull requests merged in 2023-12, with the labels that each got.

#1233 validate-icon: fix memory leaks
  src/validate-icon.c
Labels: enhancement

#1239 doc: Fix broken rST refs
  data/org.freedesktop.impl.portal.Access.xml
  data/org.freedesktop.impl.portal.Clipboard.xml
  data/org.freedesktop.impl.portal.DynamicLauncher.xml
  data/org.freedesktop.impl.portal.FileChooser.xml
  data/org.freedesktop.impl.portal.GlobalShortcuts.xml
  data/org.freedesktop.impl.portal.Inhibit.xml
  data/org.freedesktop.impl.portal.InputCapture.xml
  data/org.freedesktop.impl.portal.Notification.xml
  data/org.freedesktop.impl.portal.Print.xml
  data/org.freedesktop.impl.portal.RemoteDesktop.xml
  data/org.freedesktop.impl.portal.ScreenCast.xml
  data/org.freedesktop.portal.Account.xml
  data/org.freedesktop.portal.Background.xml
  data/org.freedesktop.portal.Camera.xml
  data/org.freedesktop.portal.Clipboard.xml
  data/org.freedesktop.portal.DynamicLauncher.xml
  data/org.freedesktop.portal.FileChooser.xml
  data/org.freedesktop.portal.GlobalShortcuts.xml
  data/org.freedesktop.portal.Inhibit.xml
  data/org.freedesktop.portal.InputCapture.xml
  data/org.freedesktop.portal.Location.xml
  data/org.freedesktop.portal.Print.xml
  data/org.freedesktop.portal.RemoteDesktop.xml
  data/org.freedesktop.portal.ScreenCast.xml
  data/org.freedesktop.portal.Screenshot.xml
  data/org.freedesktop.portal.Secret.xml
Labels: bug, documentation

#1242 docs: Add more detail to the OpenDirectory() method
  data/org.freedesktop.portal.OpenURI.xml
Labels: enhancement, documentation, portal: openuri

#1244 impl-request: Do not load properties on construction
  src/account.c
  src/background.c
  src/device.c
  src/dynamic-launcher.c
  src/email.c
  src/file-chooser.c
  src/global-shortcuts.c
  src/inhibit.c
  src/input-capture.c
  src/location.c
  src/open-uri.c
  src/print.c
  src/remote-desktop.c
  src/screen-cast.c
  src/screenshot.c
  src/secret.c
  src/wallpaper.c
Labels: enhancement

#1227 device: Improve dialog text
  src/device.c
Labels: enhancement, portal: devices

#1247 test: The test were leaving '2' files behind
  tests/test-document-fuse.sh
Labels: bug, tests

#1248 Add missing doc assets
  doc/_static/bullet.svg
  doc/_static/toc_bullet.svg
  doc/meson.build
Labels: bug, documentation

#1251 Update Czech translation
  po/cs.po
Labels: enhancement

#1252 Update the D-Bus docs URL in the help text
  src/xdg-desktop-portal.c
Labels: enhancement
