Repository flatpak/xdg-desktop-portal, pull requests merged in 2023-10, with the labels that each got.

#1119 Add FUNDING.yml
  .github/FUNDING.yml
Labels: documentation

#1097 xdg-utils: Properly quote flatpak command
  src/xdp-utils.c
Labels: bug

#1122 screencast/impl: Document 'cursor_mode' property
  data/org.freedesktop.impl.portal.ScreenCast.xml
Labels: enhancement, documentation, portal: screencast

#1127 Setup the issue template chooser
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: enhancement, ci, automation

#1134 Add bug report form
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  RELEASE_HOWTO.md
Labels: enhancement, ci

#1100 meson.build: allow linux to build without flatpak installed
  meson.build
  meson_options.txt
Labels: build system

#1139 meson.build: Increase meson version
  meson.build
Labels: enhancement, build system

#1145 docs: Rework portals.conf manpage
  doc/meson.build
  doc/portals.conf.rst.in
Labels: bug, config

#1147 docs: Add caveat on portal config file locations
  CONTRIBUTING.md
Labels: enhancement, documentation

#1153 document-portal: Fix some spelling in messages and comments
  document-portal/document-portal-fuse.c
  document-portal/document-portal.c
Labels: enhancement, portal: documents

#1155 README: add a banner
  README.md
  doc/website/assets/readme.png
Labels: enhancement, documentation

#1158 README: fix docs link
  README.md
Labels: bug, documentation

#1161 Updated website sources URL
  doc/website/_config.yml
Labels: enhancement, website

#1169 utils: Handle host apps in app_info_map_pids
  src/realtime.c
  src/xdp-utils.c
Labels: enhancement, portal: realtime

#1160 global-shortcuts: Convert timestamp to
  data/org.freedesktop.impl.portal.GlobalShortcuts.xml
  data/org.freedesktop.portal.GlobalShortcuts.xml
Labels: bug, documentation, portal: global shortcuts

#1146 docs: Document Since for FileChooser
  data/org.freedesktop.portal.FileChooser.xml
  src/file-chooser.c
  tests/limited-portals.c
  tests/test-portals.c
Labels: bug, portal: file chooser

#1114 Document the return value of AccessDialog()
  data/org.freedesktop.impl.portal.Access.xml
Labels: enhancement, documentation

#1180 gtask: make sure to call g_task_return_*()
  src/request.c
  src/session.c
Labels: enhancement

#1179 meson.build: Increase meson version
  meson.build
Labels: enhancement, build system
