Repository flatpak/xdg-desktop-portal, pull requests merged in 2024-02, with the labels that each got.

#1284 Update Turkish Translation
  po/tr.po
Labels: translation

#1289 Update Chinese translation
  po/zh_CN.po
Labels: enhancement, translation

#1291 sd-escape: Fix a comment that trips up g-ir-scanner
  src/sd-escape.c
Labels: enhancement
