Repository flatpak/xdg-desktop-portal, pull requests merged in 2024-03, with the labels that each got.

#1294 Update Polish translation 240303
  po/pl.po
Labels: translation

#1296 docs: clarify guarantees of the File Chooser API
  data/org.freedesktop.portal.FileChooser.xml
Labels: enhancement, documentation

#1297 docs: remove nonexistent FileChooser SaveFile result
  data/org.freedesktop.portal.FileChooser.xml
Labels: enhancement, documentation

#1255 fix: fallback implementation is used if preferred value of none
  src/portal-impl.c
Labels: bug, config

#1299 docs: clarify guarantees of the Screenshot API
  data/org.freedesktop.portal.Screenshot.xml
Labels: enhancement, documentation

#1300 Update Swedish translation
  po/sv.po
Labels: translation

#1315 docs: fix formatting for current_name
  data/org.freedesktop.portal.FileChooser.xml
Labels: enhancement, documentation
