Repository flatpak/xdg-desktop-portal, pull requests merged in 2024-04, with the labels that each got.

#1319 pipewire: Destroy registry object with remote
  src/pipewire.c
  src/pipewire.h
Labels: bug, pipewire

#1292 docs: Fix reference to mapping_id documentation
  data/org.freedesktop.portal.RemoteDesktop.xml
Labels: enhancement, documentation

#1306 Fix segfault when opening non-existant file
  src/open-uri.c
Labels: bug, portal: openuri

#1331 Update pofiles
  po/POTFILES.in
Labels: regression, translation

#1322 print: Add "supported_output_file_formats" option
  data/org.freedesktop.portal.Print.xml
  src/print.c
  tests/test-portals.c
Labels: enhancement, new api, portal: print

#1335 launch-context: Return a copy of the token string
  src/launch-context.c
Labels: bug

#1339 camera: Do not set permission=no on errors
  src/camera.c
Labels: enhancement, portal: camera

#1344 portal-impl: Check for default_portal before derefing it
  src/portal-impl.c
Labels: bug, config

#1345 background: Improve validation of commandline option
  src/background.c
Labels: bug, portal: background
