Repository flatpak/xdg-desktop-portal, pull requests merged in 2024-10, with the labels that each got.

#1440 Add cast and type-check functions for Session and Request
  src/background.c
  src/camera.c
  src/clipboard.c
  src/global-shortcuts.c
  src/inhibit.c
  src/input-capture.c
  src/location.c
  src/open-uri.c
  src/remote-desktop.c
  src/remote-desktop.h
  src/request.c
  src/request.h
  src/screen-cast.c
  src/screenshot.c
  src/session.c
  src/session.h
  src/wallpaper.c
Labels: enhancement

#1347 doc: Add ScreenCast source type meaning
  data/org.freedesktop.impl.portal.ScreenCast.xml
  data/org.freedesktop.portal.ScreenCast.xml
Labels: portal: screencast

#1450 Fix some memory leaks
  src/settings.c
  src/xdp-app-info-flatpak.c
Labels: portal: settings

#1452 Update Chinese translation
  po/zh_CN.po
Labels: translation

#1453 README: Slim down the content and link to the website instead
  README.md
Labels: documentation, website

#1460 doc: Link to github discussions, issues and pull request pages
  doc/pull-requests.rst
Labels: documentation

#1465 Release workflow improvements
  .github/workflows/release.yml
Labels: ci, automation

#1467 settings: Make the text about non-standardized keys prominent
  data/org.freedesktop.portal.Settings.xml
Labels: documentation, portal: settings

#1471 ci: Use images from actor instead of owner
  .github/workflows/container.yml
Labels: ci

#1476 Update Portuguese translation
  po/pt.po
Labels: translation

#1473 Implement a signal handler to help with asan
  src/xdg-desktop-portal.c
Labels: enhancement

#1472 ci: Use images from actor for pull requests
  .github/workflows/container.yml
Labels: ci

#1480 ci: Prefer repository owner image if it exists
  .github/workflows/container.yml
Labels: ci

#1482 tests/location: Delete leftover location test source file
  tests/limited-portals.c
  tests/location.c
Labels: tests

#1478 Avoid forwarding all notification file desciptors to backend
  src/notification.c
Labels: regression

#1485 ci: Install doc dependencies via pip
  .github/workflows/Containerfile
  .github/workflows/container.yml
  .github/workflows/pages.yml
Labels: documentation, website

#1484 Disable broken test
  tests/notification.c
  tests/test-portals.c
Labels: tests

#1489 Update Occitan translation
  po/oc.po
Labels: translation

#1358 portal-impl: Use fallback portals for Settings as well
  src/portal-impl.c
Labels: config

#1501 Update Indonesian translation
  po/id.po
Labels: translation
