Repository flatpak/xdg-desktop-portal, pull requests merged in 2024-09, with the labels that each got.

#1428 pages: Update various actions
  .github/workflows/pages.yml
Labels: website

#1432 Update British English translation
  po/en_GB.po
Labels: translation

#1443 Updated Hebrew Translation
  po/he.po
Labels: translation

#1447 doc: Fix Background Monitor Apps ref link
  doc/for-desktop-developers.rst
Labels: documentation
