Repository flatpak/xdg-desktop-portal, pull requests merged in 2024-12, with the labels that each got.

#1529 usb: Fix the incorrect documentation of the D-Bus Interface
  data/org.freedesktop.impl.portal.Usb.xml
Labels: documentation, portal: usb

#1534 org.freedesktop.portal.Notification: clarify icon validation requirem…
  data/org.freedesktop.portal.Notification.xml
  doc/icons.rst
  doc/meson.build
Labels: documentation

#1541 ci: Set XDP_TEST_IN_CI in the release workflow too
  .github/workflows/release.yml
Labels: ci
