Repository flatpak/xdg-desktop-portal, pull requests merged in 2024-06, with the labels that each got.

#1374 Add Japanese translation
  po/LINGUAS
  po/ja.po
Labels: translation

#1372 document/fuse: Provide the document host path as xattr
  data/org.freedesktop.portal.Documents.xml
  document-portal/document-portal-fuse.c
Labels: enhancement, portal: documents

#1381 globalshortcuts: Fix copy-paste errors in the docs
  data/org.freedesktop.impl.portal.GlobalShortcuts.xml
Labels: documentation, portal: global shortcuts

#1383 globalshortcuts: Add a link to the xdg shortcuts spec
  data/org.freedesktop.portal.GlobalShortcuts.xml
Labels: documentation

#1302 docs: note and describe how to develop in toolbox
  doc/contributing.rst
Labels: enhancement, documentation

#1384 Make contribution link in README.md direct instead of requiring more clicks
  README.md
Labels: documentation

#1389 tests: Fix mistake in notification tests
  tests/notification.c
Labels: tests
