Repository flatpak/xdg-desktop-portal, pull requests merged in 2025-03, with the labels that each got.

#1651 Added Bulgarian translation
  po/LINGUAS
  po/bg.po
Labels: translation

#1660 Update Catalan translation
  po/ca.po
Labels: translation

#1655 realtime: Include PID/TID in some error messages
  src/realtime.c
Labels: portal: realtime

#1666 doc: Fix a few typos and wrong references
  data/org.freedesktop.impl.portal.GlobalShortcuts.xml
  data/org.freedesktop.portal.GlobalShortcuts.xml
  data/org.freedesktop.portal.RemoteDesktop.xml
  data/org.freedesktop.portal.Screenshot.xml
  doc/api-reference.rst
Labels: documentation, portal: global shortcuts

#1668 doc: Add icons for Icons Common Conventions
  doc/img/tiles/Icons-d.png
  doc/img/tiles/Icons-l.png
Labels: documentation
