Repository flatpak/xdg-desktop-portal, pull requests merged in 2025-02, with the labels that each got.

#1622 Update sl.po
  po/sl.po
Labels: translation

#1621 Update Turkish translation
  po/tr.po
Labels: translation

#1626 test: Fix calling pytest from meson
  tests/meson.build
Labels: tests

#1634 Add the Go package to list of libraries
  doc/convenience-libraries.rst
Labels: documentation

#1636 usb: docs: Fix links to Session and Request
  data/org.freedesktop.portal.Usb.xml
Labels: documentation, portal: usb

#1642 tests/README: Explain the unit and integration test systems
  tests/README.md
Labels: documentation
